import './assets/fontawesome-free-6.4.2-web/css/all.css'
import './assets/css/root.css'
import './assets/css/main.css'


import './assets/css/modules/line-loader.css'
import './assets/css/admin/admin.css'
import './assets/css/admin/index-list-element.css'
import './assets/css/admin/index-list-employee.css'
import './assets/css/admin/index-list-city.css'
import './assets/css/admin/create-form.css'
import './assets/css/admin/create-form-employee.css'
import './assets/css/admin/left-side-menu.css'
import './assets/css/admin/admin-restaurant-show.css'
import './assets/css/admin/admin-restaurant-index.css'


import './assets/css/client/container.css'
import './assets/css/client/info.css'
import './assets/css/client/header.css'
import './assets/css/client/burger-menu.css'
import './assets/css/client/categories.css'
import './assets/css/client/content.css'
import './assets/css/client/product-card.css'
import './assets/css/client/bottom-device-menu.css'
import './assets/css/client/order-settings.css'
import './assets/css/client/city-selecte.css'
import './assets/css/client/btn.css'
import './assets/css/client/btn-submit.css'
import './assets/css/client/btn-inactive.css'
import './assets/css/client/phone-input.css'
import './assets/css/client/code-input.css'
import './assets/css/client/spinner.css'
import './assets/css/client/error-loading.css'
import './assets/css/client/active-order.css'
import './assets/css/client/client-menu.css'

import './assets/css/client/popup-pages/address-panel.css'
import './assets/css/client/popup-pages/cart-panel.css'
import './assets/css/client/popup-pages/client-popup-page-layout.css'
import './assets/css/client/popup-pages/login-panel.css'
import './assets/css/client/popup-pages/order-panel.css'
import './assets/css/client/popup-pages/order-status-panel.css'
import './assets/css/client/popup-pages/orders-history.css'
import './assets/css/client/popup-pages/user-panel.css'
import './assets/css/client/popup-pages/user-edit-panel.css'

import './assets/css/client/parts/client-menu-cart-panel.css'


import './assets/css/order-manager/order-manager-main.css'
import './assets/css/order-manager/order-manager-mini-order.css'
import './assets/css/order-manager/order-manager-full-order.css'
