import './assets/fontawesome-free-6.4.2-web/css/all.css'
import './assets/css/root.css'
import './assets/css/main.css'

import './assets/css/admin/admin.css'
import './assets/css/admin/index-list-element.css'
import './assets/css/admin/index-list-employee.css'
import './assets/css/admin/index-list-city.css'
import './assets/css/admin/create-form.css'
import './assets/css/admin/create-form-employee.css'
import './assets/css/admin/left-side-menu.css'


import './assets/css/client/container.css'
import './assets/css/client/info.css'
import './assets/css/client/header.css'
import './assets/css/client/burger-menu.css'
import './assets/css/client/cart-panel.css'
import './assets/css/client/categories.css'
import './assets/css/client/content.css'
import './assets/css/client/product-card.css'
import './assets/css/client/bottom-device-menu.css'
import './assets/css/client/popup.css'
import './assets/css/client/dialog.css'
import './assets/css/client/client-main.css'
import './assets/css/client/order-settings.css'
import './assets/css/client/city-settings.css'
import './assets/css/client/client-btn-submit.css'
